Updated configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1010,11 +1010,9 @@ Optional Features:
   --enable-static=PKGS  build static libraries default=yes
   --enable-fast-install=PKGS  optimize for fast installation default=yes
   --disable-libtool-lock  avoid locking (might break parallel builds)
-\
-  --enable-modules=mods Enable one or more modules; all modules
-                          found in the current directory are enabled
-                          by default.  Specify \"no\" (without quotes)
-                          to build server only
+  --enable-modules=mods   Enable one or more modules; all modules found in the
+                          current directory are enabled by default. Specify
+                          "no" (without quotes) to build server only
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1025,8 +1023,12 @@ Optional Packages:
   --with-pedantic         Add -pedantic to compile options
   --with-optimization     Optimize the executables
   --with-prof             Generate profiling information
-  --with-pgsql=PGSQLDIR   Specify location to find pgsql, default is
-                          \"/usr/local/pgsql\"
+  --with-pgsqllib=PGSQLLIBDIR
+                          Specify location to find libpq++.so, default is
+                          /usr/local/pgsql/lib
+  --with-pgsqlinclude=PGSQLINCLUDEDIR
+                          Specify location to find libpq++.h, default is
+                          /usr/local/pgsql/include
 
 Some influential environment variables:
   CC          C compiler command
@@ -4264,7 +4266,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4267 "configure"' > conftest.$ac_ext
+  echo '#line 4269 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4800,7 +4802,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:4803: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:4805: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6593,7 +6595,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6596 "configure"
+#line 6598 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -6691,7 +6693,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6694 "configure"
+#line 6696 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9873,120 +9875,6 @@ fi
 done
 
 
-for ac_header in hash_map
-do
-as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
-if eval "test \"\${$as_ac_Header+set}\" = set"; then
-  echo "$as_me:$LINENO: checking for $ac_header" >&5
-echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
-if eval "test \"\${$as_ac_Header+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
-else
-  # Is the header compilable?
-echo "$as_me:$LINENO: checking $ac_header usability" >&5
-echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-$ac_includes_default
-#include <$ac_header>
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_header_compiler=yes
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-ac_header_compiler=no
-fi
-rm -f conftest.$ac_objext conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
-echo "${ECHO_T}$ac_header_compiler" >&6
-
-# Is the header present?
-echo "$as_me:$LINENO: checking $ac_header presence" >&5
-echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-#include <$ac_header>
-_ACEOF
-if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
-  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-  ac_status=$?
-  egrep -v '^ *\+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } >/dev/null; then
-  if test -s conftest.err; then
-    ac_cpp_err=$ac_cxx_preproc_warn_flag
-  else
-    ac_cpp_err=
-  fi
-else
-  ac_cpp_err=yes
-fi
-if test -z "$ac_cpp_err"; then
-  ac_header_preproc=yes
-else
-  echo "$as_me: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  ac_header_preproc=no
-fi
-rm -f conftest.err conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
-echo "${ECHO_T}$ac_header_preproc" >&6
-
-# So?  What about this header?
-case $ac_header_compiler:$ac_header_preproc in
-  yes:no )
-    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;};;
-  no:yes )
-    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
-echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: $ac_header: check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;};;
-esac
-echo "$as_me:$LINENO: checking for $ac_header" >&5
-echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
-if eval "test \"\${$as_ac_Header+set}\" = set"; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  eval "$as_ac_Header=$ac_header_preproc"
-fi
-echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
-echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
-
-fi
-if test `eval echo '${'$as_ac_Header'}'` = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
-_ACEOF
-
-fi
-
-done
-
-
 echo "$as_me:$LINENO: checking for ANSI C header files" >&5
 echo $ECHO_N "checking for ANSI C header files... $ECHO_C" >&6
 if test "${ac_cv_header_stdc+set}" = set; then
@@ -10591,37 +10479,73 @@ if test "${with_prof+set}" = set; then
 
 fi;
 
-PGSQL_PREFIX=/usr/local/pgsql
+PGSQL_LIB=/usr/local/pgsql/lib
+searchForLib=yes
 
-
-# Check whether --with-pgsql or --without-pgsql was given.
-if test "${with_pgsql+set}" = set; then
-  withval="$with_pgsql"
-  PGSQL_PREFIX=$withval
+# Check whether --with-pgsql-lib or --without-pgsql-lib was given.
+if test "${with_pgsql_lib+set}" = set; then
+  withval="$with_pgsql_lib"
+  PGSQL_LIB=$withval
+	 searchForLib=no
 
 fi;
 
-echo "$as_me:$LINENO: checking for libpq++.h" >&5
+PGSQL_INCLUDE=/usr/local/pgsql/include
+searchForInclude=yes
+
+# Check whether --with-pgsql-include or --without-pgsql-include was given.
+if test "${with_pgsql_include+set}" = set; then
+  withval="$with_pgsql_include"
+  PGSQLINCLUDE=$withval
+	 searchForInclude=no
+
+fi;
+
+if test $searchForInclude = yes; then
+	echo "$as_me:$LINENO: checking for libpq++.h" >&5
 echo $ECHO_N "checking for libpq++.h... $ECHO_C" >&6
-if test -f "$PGSQL_PREFIX/include/libpq++.h"; then
-	PGSQL_INCLUDE="$PGSQL_PREFIX/include"
-	PGSQL_LIB="$PGSQL_PREFIX/lib"
-elif test -f "/usr/local/include/libpq++.h"; then
-	PGSQL_INCLUDE=/usr/local/include
-	PGSQL_LIB=/usr/local/lib
-elif test -f "/usr/include/postgresql/libpq++.h"; then
-	PGSQL_INCLUDE=/usr/include/postgresql
-	PGSQL_LIB=/usr/lib/pgsql
-elif test -f "/usr/include/pgsql/libpq++.h"; then
-	PGSQL_INCLUDE=/usr/include/pgsql
-	PGSQL_LIB=/usr/lib/pgsql
-else
-        { { echo "$as_me:$LINENO: error: Unable to find PostGreSQL " >&5
-echo "$as_me: error: Unable to find PostGreSQL " >&2;}
+	if test -f "$PGSQL_INCLUDE/libpq++.h"; then
+		/bin/true
+	elif test -f "/usr/local/include/libpq++.h"; then
+		PGSQL_INCLUDE=/usr/local/include
+	elif test -f "/usr/include/postgresql/libpq++.h"; then
+		PGSQL_INCLUDE=/usr/include/postgresql
+	elif test -f "/usr/include/pgsql/libpq++.h"; then
+		PGSQL_INCLUDE=/usr/include/pgsql
+	else
+	        { { echo "$as_me:$LINENO: error: Unable to find libpq++.h " >&5
+echo "$as_me: error: Unable to find libpq++.h " >&2;}
    { (exit 1); exit 1; }; }
-fi
-echo "$as_me:$LINENO: result: yes" >&5
+	fi
+	echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
+fi
+
+if test $searchForLib = yes; then
+	echo "$as_me:$LINENO: checking for libpq++.so" >&5
+echo $ECHO_N "checking for libpq++.so... $ECHO_C" >&6
+	if test -f "$PGSQL_LIB/libpq++.so"; then
+		/bin/true
+	elif test -f "/usr/local/lib/libpq++.so"; then
+		PGSQL_LIB=/usr/local/lib
+	elif test -f "/usr/lib/libpq++.so"; then
+		PGSQL_LIB=/usr/lib
+	elif test -f "/usr/lib/postgresql/libpq++.so"; then
+		PGSQL_LIB=/usr/lib/postgresql
+	elif test -f "/usr/lib/pgsql/libpq++.so"; then
+		PGSQL_LIB=/usr/lib/pgsql
+	elif test -f "/usr/local/pgsql/lib/libpq++.so"; then
+		PGSQL_LIB=/usr/local/pgsql/lib
+	elif test -f "/usr/local/postgresql/lib/libpq++.so"; then
+		PGSQL_LIB=/usr/local/postgresql/lib
+	else
+	        { { echo "$as_me:$LINENO: error: Unable to find libpq++.so" >&5
+echo "$as_me: error: Unable to find libpq++.so" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+	echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+fi
 
 
 CXXFLAGS="$CXXFLAGS -I`pwd`/include -I`pwd`/lib"
