Fixed a compile warning in REMUSERCommand.cc Hopefully fixed a compile bug with the pair struct

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.31 .
+# From configure.in Revision: 1.32 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.
 #
@@ -8627,27 +8627,6 @@ fi
 
 fi
 
-echo "$as_me:8630: checking for struct linger" >&5
-echo $ECHO_N "checking for struct linger... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-#line 8633 "configure"
-#include "confdefs.h"
-#include <sys/socket.h>
-
-_ACEOF
-if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
-  egrep "struct( |	)*linger" >/dev/null 2>&1; then
-  echo "$as_me:8640: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-else
-  cat >>confdefs.h <<\EOF
-#define NO_STRUCT_LINGER 1
-EOF
- echo "$as_me:8646: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-rm -f conftest*
-
 useDebug=yes
 
 # Check whether --with-debug or --without-debug was given.
@@ -8685,7 +8664,7 @@ if test "${with_pgsql+set}" = set; then
 
 fi;
 
-echo "$as_me:8688: checking for libpq++.h" >&5
+echo "$as_me:8667: checking for libpq++.h" >&5
 echo $ECHO_N "checking for libpq++.h... $ECHO_C" >&6
 if test -f "$PGSQL_PREFIX/include/libpq++.h"; then
 	PGSQL_INCLUDE="/usr/local/pgsql/include"
@@ -8700,11 +8679,11 @@ elif test -f "/usr/include/pgsql/libpq++.h"; then
 	PGSQL_INCLUDE=/usr/include/pgsql
 	PGSQL_LIB=/usr/lib/pgsql
 else
-        { { echo "$as_me:8703: error: Unable to find PostGreSQL " >&5
+        { { echo "$as_me:8682: error: Unable to find PostGreSQL " >&5
 echo "$as_me: error: Unable to find PostGreSQL " >&2;}
    { (exit 1); exit 1; }; }
 fi
-echo "$as_me:8707: result: yes" >&5
+echo "$as_me:8686: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
 CXXFLAGS="$CXXFLAGS -I`pwd`/include -I`pwd`/lib"
@@ -8840,7 +8819,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:8843: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:8822: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -9016,7 +8995,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:9019: error: ambiguous option: $1
+    { { echo "$as_me:8998: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -9035,7 +9014,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:9038: error: unrecognized option: $1
+  -*) { { echo "$as_me:9017: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -9092,7 +9071,7 @@ do
   "mod.stats/Makefile" ) CONFIG_FILES="$CONFIG_FILES mod.stats/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "include/defs.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/defs.h" ;;
-  *) { { echo "$as_me:9095: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:9074: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -9349,7 +9328,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:9352: creating $ac_file" >&5
+    { echo "$as_me:9331: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -9367,7 +9346,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:9370: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:9349: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -9380,7 +9359,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:9383: error: cannot find input file: $f" >&5
+           { { echo "$as_me:9362: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -9441,7 +9420,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:9444: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:9423: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -9452,7 +9431,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:9455: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:9434: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -9465,7 +9444,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:9468: error: cannot find input file: $f" >&5
+           { { echo "$as_me:9447: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -9582,7 +9561,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:9585: $ac_file is unchanged" >&5
+      { echo "$as_me:9564: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -9744,7 +9723,7 @@ if test "$no_recursion" != yes; then
     # parts of a large source tree are present.
     test -d $srcdir/$ac_subdir || continue
 
-    { echo "$as_me:9747: configuring in $ac_subdir" >&5
+    { echo "$as_me:9726: configuring in $ac_subdir" >&5
 echo "$as_me: configuring in $ac_subdir" >&6;}
     case $srcdir in
     .) ;;
@@ -9766,7 +9745,7 @@ done; }
 
        if test -d ./$ac_subdir; then :;
        else
-         { { echo "$as_me:9769: error: cannot create \`pwd\`/$ac_subdir" >&5
+         { { echo "$as_me:9748: error: cannot create \`pwd\`/$ac_subdir" >&5
 echo "$as_me: error: cannot create \`pwd\`/$ac_subdir" >&2;}
    { (exit 1); exit 1; }; }
        fi
@@ -9797,7 +9776,7 @@ echo "$as_me: error: cannot create \`pwd\`/$ac_subdir" >&2;}
     elif test -f $ac_sub_srcdir/configure.in; then
       ac_sub_configure=$ac_configure
     else
-      { echo "$as_me:9800: WARNING: no configuration information is in $ac_subdir" >&5
+      { echo "$as_me:9779: WARNING: no configuration information is in $ac_subdir" >&5
 echo "$as_me: WARNING: no configuration information is in $ac_subdir" >&2;}
       ac_sub_configure=
     fi
@@ -9811,12 +9790,12 @@ echo "$as_me: WARNING: no configuration information is in $ac_subdir" >&2;}
         ac_sub_cache_file=$ac_dots$cache_file ;;
       esac
 
-      { echo "$as_me:9814: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&5
+      { echo "$as_me:9793: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&5
 echo "$as_me: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&6;}
       # The eval makes quoting arguments work.
       eval $ac_sub_configure $ac_sub_configure_args \
            --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir ||
-        { { echo "$as_me:9819: error: $ac_sub_configure failed for $ac_subdir" >&5
+        { { echo "$as_me:9798: error: $ac_sub_configure failed for $ac_subdir" >&5
 echo "$as_me: error: $ac_sub_configure failed for $ac_subdir" >&2;}
    { (exit 1); exit 1; }; }
     fi
