Fixed a silly bug in the pgsql detection scheme

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8408,7 +8408,8 @@ fi;
 echo "$as_me:8408: checking for libpq++.h" >&5
 echo $ECHO_N "checking for libpq++.h... $ECHO_C" >&6
 if test -f "$PGSQL_PREFIX/include/libpq++.h"; then
-	true
+	PGSQL_INCLUDE="/usr/local/pgsql/include"
+	PGSQL_LIB="/usr/local/pgsql/lib"
 elif test -f "/usr/local/include/libpq++.h"; then
 	PGSQL_INCLUDE=/usr/local/include
 	PGSQL_LIB=/usr/local/lib
@@ -8419,11 +8420,11 @@ elif test -f "/usr/include/pgsql/libpq++.h"; then
 	PGSQL_INCLUDE=/usr/include/pgsql
 	PGSQL_LIB=/usr/lib/pgsql
 else
-        { { echo "$as_me:8422: error: Unable to find PostGreSQL " >&5
+        { { echo "$as_me:8423: error: Unable to find PostGreSQL " >&5
 echo "$as_me: error: Unable to find PostGreSQL " >&2;}
    { (exit 1); exit 1; }; }
 fi
-echo "$as_me:8426: result: yes" >&5
+echo "$as_me:8427: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
 CXXFLAGS="$CXXFLAGS -I`pwd`/include -I`pwd`/lib"
@@ -8555,7 +8556,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:8558: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:8559: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -8731,7 +8732,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:8734: error: ambiguous option: $1
+    { { echo "$as_me:8735: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -8750,7 +8751,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:8753: error: unrecognized option: $1
+  -*) { { echo "$as_me:8754: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -8804,7 +8805,7 @@ do
   "mod.stats/Makefile" ) CONFIG_FILES="$CONFIG_FILES mod.stats/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "include/defs.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/defs.h" ;;
-  *) { { echo "$as_me:8807: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:8808: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -9049,7 +9050,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:9052: creating $ac_file" >&5
+    { echo "$as_me:9053: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -9067,7 +9068,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:9070: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:9071: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -9080,7 +9081,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:9083: error: cannot find input file: $f" >&5
+           { { echo "$as_me:9084: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -9141,7 +9142,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:9144: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:9145: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -9152,7 +9153,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:9155: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:9156: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -9165,7 +9166,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:9168: error: cannot find input file: $f" >&5
+           { { echo "$as_me:9169: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -9282,7 +9283,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:9285: $ac_file is unchanged" >&5
+      { echo "$as_me:9286: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -9400,7 +9401,7 @@ if test "$no_recursion" != yes; then
     # parts of a large source tree are present.
     test -d $srcdir/$ac_subdir || continue
 
-    { echo "$as_me:9403: configuring in $ac_subdir" >&5
+    { echo "$as_me:9404: configuring in $ac_subdir" >&5
 echo "$as_me: configuring in $ac_subdir" >&6;}
     case $srcdir in
     .) ;;
@@ -9422,7 +9423,7 @@ done; }
 
        if test -d ./$ac_subdir; then :;
        else
-         { { echo "$as_me:9425: error: cannot create \`pwd\`/$ac_subdir" >&5
+         { { echo "$as_me:9426: error: cannot create \`pwd\`/$ac_subdir" >&5
 echo "$as_me: error: cannot create \`pwd\`/$ac_subdir" >&2;}
    { (exit 1); exit 1; }; }
        fi
@@ -9453,7 +9454,7 @@ echo "$as_me: error: cannot create \`pwd\`/$ac_subdir" >&2;}
     elif test -f $ac_sub_srcdir/configure.in; then
       ac_sub_configure=$ac_configure
     else
-      { echo "$as_me:9456: WARNING: no configuration information is in $ac_subdir" >&5
+      { echo "$as_me:9457: WARNING: no configuration information is in $ac_subdir" >&5
 echo "$as_me: WARNING: no configuration information is in $ac_subdir" >&2;}
       ac_sub_configure=
     fi
@@ -9467,12 +9468,12 @@ echo "$as_me: WARNING: no configuration information is in $ac_subdir" >&2;}
         ac_sub_cache_file=$ac_dots$cache_file ;;
       esac
 
-      { echo "$as_me:9470: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&5
+      { echo "$as_me:9471: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&5
 echo "$as_me: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&6;}
       # The eval makes quoting arguments work.
       eval $ac_sub_configure $ac_sub_configure_args \
            --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir ||
-        { { echo "$as_me:9475: error: $ac_sub_configure failed for $ac_subdir" >&5
+        { { echo "$as_me:9476: error: $ac_sub_configure failed for $ac_subdir" >&5
 echo "$as_me: error: $ac_sub_configure failed for $ac_subdir" >&2;}
    { (exit 1); exit 1; }; }
     fi
